---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-kms-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - aliases
  - grants
  - keys
  verbs:
  - get
  - list
  - watch
