apiVersion: v2
appVersion: 1.16.0
description: A chart that issues HTTPS certificates on Porter.
icon: https://cdn4.iconfinder.com/data/icons/macster-2/100/https__-512.png
name: https-issuer
type: application
version: 0.7.0
