---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-dynamodb-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - dynamodb.services.k8s.aws
  resources:
  - backups
  - globaltables
  - tables
  verbs:
  - get
  - list
  - watch
