labels: {}

annotations: {}

storageClass:
  reclaimPolicy: "Retain"
  volumeBindingMode: "Immediate"
  directoryPerms: "777"
  reuseAccessPoint: "true"
  efs:
    enabled: true
    fileSystemId: "fs-042d04a019267cbe5"
    provisioningMode: "efs-ap"
    provisioner: efs.csi.aws.com

persistentVolume:
  capacity: "5Gi"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem

persistentVolumeClaim:
  requestStorage: "5Gi"
  accessModes:
    - ReadWriteMany
