{{- if .Values.complianceReconciler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager-compliance
  annotations:
    porter.run/agent-major-version: "v3"
    porter.run/agent-version: "{{ .Chart.Version }}"
  name: porter-agent-controller-manager-compliance
  namespace: porter-agent-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      control-plane: controller-manager-compliance
  template:
    metadata:
      labels:
        control-plane: controller-manager-compliance
    spec:
      containers:
      - image: "{{ .Values.agent.image }}"
        imagePullPolicy: Always
        command: ["/porter/agent"]
        args: ["compliance"]
        envFrom:
        - configMapRef:
            name: porter-agent-config
        ports:
        - containerPort: 10001
          name: http
        name: manager
        livenessProbe:
          httpGet:
            path: /livez
            port: 10001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 10001
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: {{ .Values.complianceReconciler.resources.requests.cpu }}
            memory: {{ .Values.complianceReconciler.resources.requests.memory }}
          limits:
            cpu: {{ .Values.complianceReconciler.resources.limits.cpu }}
            memory: {{ .Values.complianceReconciler.resources.limits.memory }}
        securityContext:
          allowPrivilegeEscalation: false
      {{- if .Values.agent.privateRegistry.enabled }}
      imagePullSecrets:
        - name: "{{ .Values.agent.privateRegistry.secret }}"
      {{- end }}
      serviceAccountName: porter-agent-controller-manager
      terminationGracePeriodSeconds: 10
      {{- if gt (len .Values.nodeSelector) 0}}
      nodeSelector:
        {{- range $k, $v := .Values.nodeSelector }}
        {{ $k }}: {{ $v }}
        {{- end }}
      {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
{{- end }} 