apiVersion: v1
kind: ServiceAccount
metadata:
  name: porter-agent-controller-manager
  namespace: porter-agent-system
  {{- if and .Values.agent.serviceAccount .Values.agent.serviceAccount.annotations (gt (len .Values.agent.serviceAccount.annotations) 0) }}
  annotations:
    {{- range $key, $value := .Values.agent.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

