---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-sfn-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - sfn.services.k8s.aws
  resources:
  - activities
  - statemachines
  verbs:
  - get
  - list
  - watch
