{{- if .Values.memcachedPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  memcached-password: {{ .Values.memcachedPassword | b64enc | quote }}
{{- end }}
