{{- if .Values.controller.wallarm.enabled -}}
apiVersion: v1
data:
  token: {{ .Values.controller.wallarm.token | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "ingress-nginx.wallarmSecret" . }}
type: Opaque
{{- end }}
