{{- if .Values.controller.wallarm.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.controller.wallarm.tarantool.service.annotations }}
  annotations: {{ toYaml .Values.controller.wallarm.tarantool.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- if .Values.controller.wallarm.tarantool.service.labels }}
    {{- toYaml .Values.controller.wallarm.tarantool.service.labels | nindent 4 }}
  {{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}-wallarm-tarantool
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: tarantool
      port: {{ template "ingress-nginx.wallarmTarantoolPort" . }}
      protocol: TCP
  selector:
    {{- include "ingress-nginx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "ingress-nginx.wallarmTarantoolName" . }}
{{- end }}
