apiVersion: v1
name: dynamodb-chart
description: A Helm chart for the ACK service controller for Amazon DynamoDB (DynamoDB)
version: 1.2.6
appVersion: 1.2.6
home: https://github.com/aws-controllers-k8s/dynamodb-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/dynamodb-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: DynamoDB Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/dynamodb-maintainer
keywords:
  - aws
  - kubernetes
  - dynamodb
