apiVersion: v2
description: A Helm chart to deploy New Relic Kubernetes Logging as a DaemonSet, supporting both Linux and Windows nodes and containers
name: newrelic-logging
version: 1.10.11
appVersion: 1.10.0
home: https://github.com/newrelic/kubernetes-logging
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg
maintainers:
  - name: jsubirat
    email: logging-team@newrelic.com
  - name: tejunior
  - name: jodstrcil
  - name: edmocosta
  - name: Noly
  - name: danybmx
keywords:
  - logging
  - newrelic
dependencies:
  - name: common-library
    version: 1.0.4
    repository: "https://helm-charts.newrelic.com"
