apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-memorydb-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ else }}
kind: Role
metadata:
  creationTimestamp: null
  name: ack-memorydb-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups/status
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets/status
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys/status
  verbs:
  - get
  - list
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - acls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - acls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - parametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - parametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - subnetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - subnetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sns.services.k8s.aws
  resources:
  - topics
  verbs:
  - get
  - list
- apiGroups:
  - sns.services.k8s.aws
  resources:
  - topics/status
  verbs:
  - get
  - list
