---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.config.name }}.1"
  namespace: porter-env-group
  labels:
    porter.run/environment-group-name: "{{ .Values.config.name }}"
    porter.run/environment-group-version: "1"
    porter.run/environment-group-datastore: "{{ .Values.config.name }}"
    porter.run/environment-group-datastore-type: postgresql-aurora
    porter.run/managed: "true"
    porter.run/helm-release-name: "{{ .Release.Name }}"
data:
  DB_PASS: "{{- include "random_pw_reusable" . | b64enc }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.config.name }}.1"
  namespace: porter-env-group
  labels:
    porter.run/environment-group-name: "{{ .Values.config.name }}"
    porter.run/environment-group-version: "1"
    porter.run/environment-group-datastore: "{{ .Values.config.name }}"
    porter.run/environment-group-datastore-type: postgresql-aurora
    porter.run/managed: "true"
    porter.run/helm-release-name: "{{ .Release.Name }}"
data:
  DB_PORT: "5432"
  DB_USER: "{{ .Values.config.masterUsername }}"
---
apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: "{{ .Values.config.name }}-host"
  namespace: "{{ .Release.Namespace }}"
  labels:
    porter.run/helm-release-name: "{{ .Release.Name }}"
spec:
  to:
    name: "{{ .Values.config.name }}.1"
    namespace: porter-env-group
    key: DB_HOST
    kind: configmap
  from:
    path: ".status.endpoint"
    resource:
      group: rds.services.k8s.aws
      kind: DBCluster
      name: "{{ .Values.config.name }}"
