---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-eventbridge-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - eventbridge.services.k8s.aws
  resources:
  - archives
  - endpoints
  - eventbuses
  - rules
  verbs:
  - get
  - list
  - watch
