apiVersion: v1
name: prometheus-adapter
version: 0.1.0
appVersion: v0.11.2
description: A Helm chart for k8s prometheus adapter
home: https://github.com/kubernetes-sigs/prometheus-adapter
keywords:
  - hpa
  - metrics
  - prometheus
  - adapter
sources:
  - https://github.com/kubernetes/charts
  - https://github.com/kubernetes-sigs/prometheus-adapter
maintainers:
  - name: mattiasgees
    email: mattias.gees@jetstack.io
  - name: steven-sheehy
  - name: hectorj2f
    email: hfernandez@mesosphere.com
