apiVersion: v2
appVersion: 3.8.2
description: Mezmo(LogDNA) collector agent daemonset for Kubernetes.
home: https://logdna.com
icon: https://logdna.com/assets/images/logdna_logo_240w.png
keywords:
  - logs
  - logging
  - log-management
  - agent
  - alerts
  - metrics
  - events
  - daemonset
  - logger
maintainers:
  - email: help@logdna.com
    name: LogDNA
name: mezmo-agent
sources:
  - https://github.com/logdna/logdna-agent-v2
type: application
version: 0.1.0
