apiVersion: v2
appVersion: 3.8.2
description: LogDNA collector agent daemonset for Kubernetes.
home: https://logdna.com
icon: https://avatars.githubusercontent.com/u/17461937?s=200&v=4
keywords:
  - logs
  - logging
  - log-management
  - agent
  - alerts
  - metrics
  - events
  - daemonset
  - logger
  - APP
  - LOGGING
maintainers:
  - email: help@logdna.com
    name: logdna
name: logdna
sources:
  - https://github.com/logdna/logdna-agent-v2
type: application
version: 0.1.0