{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
  name: {{ include "newrelic.common.naming.fullname" . }}
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - "daemonsets"
  - "events"
  - "namespaces"
  - "nodes"
  - "pods"
  - "services"
  verbs:
  - "get"
  - "watch"
  - "list"
{{- end -}}
