{{ if .Values.autoscaling.enabled }} 
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: {{ .Release.Name }}-hf-llm
spec:
    hosts:
    - {{ .Release.Name }}.porter.llm
    scaleTargetRef:
        name: {{ .Release.Name }}-hf-llm 
        service: {{ .Release.Name }}-hf-llm
        port: 8000
    replicas:
        min: {{ .Values.autoscaling.minReplicas }} 
        max: {{ .Values.autoscaling.maxReplicas }}
    scaledownPeriod: {{ .Values.autoscaling.scaledownPeriod }}
    scalingMetric:
        concurrency:
            targetValue: {{ .Values.autoscaling.targetConcurrency }}
{{- end }}
