apiVersion: v1
kind: Service
metadata:
  labels:
    llm-model: {{ .Release.Name }}-hf-llm
  name: {{ .Release.Name }}-hf-llm
spec:
  ports:
    - name: https
      port: 8000
      targetPort: https
  selector:
    llm-model: {{ .Release.Name }}-hf-llm