apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-{{ .Release.Name }}-hf-llm
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: {{ .Values.efsFileSystemId }}
  reuseAccessPoint: "true"