{{- $fullName := include "container-agent.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "container-agent.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels: {{- toYaml .Values.agent.matchLabels | nindent 6 }}
  template:
    metadata:
      labels: {{- toYaml .Values.agent.matchLabels | nindent 8 }}
      annotations:
        checksum/config: {{ .Values.agent.resourceClasses | toString | sha256sum }}
      {{- range $key, $value := .Values.agent.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
    {{- if .Values.agent.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.agent.pullSecrets }}
        - {{ toYaml . }}
      {{- end}}
    {{- end }}
      serviceAccountName: {{ include "container-agent.serviceAccountName" . }}
    {{- if .Values.agent.podSecurityContext }}
      securityContext: {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
    {{- end }}
    {{- if .Values.agent.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.agent.terminationGracePeriodSeconds }}
    {{- end }}
      volumes:
        - name: taskpod-config
          configMap:
            name: {{ include "container-agent.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.agent.image }}
          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
        {{- if .Values.agent.containerSecurityContext }}
          securityContext: {{- toYaml .Values.agent.containerSecurityContext | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: taskpod-config
              mountPath: /etc/container-agent
          env:
            - name: RUNNER_API
              value: {{ .Values.agent.runnerAPI }}
            - name: AGENT_NAME
              value: {{ .Values.agent.name | default (include "container-agent.fullname" .) }}
            - name: O11Y_LEVEL
              value: {{ .Values.agent.loggingLevel | quote }}
            - name: MAX_RUN_TIME
              value: {{ .Values.agent.maxRunTime }}
            - name: MAX_CONCURRENT_TASKS
              value: {{ .Values.agent.maxConcurrentTasks | quote }}
            - name: CHECK_ENABLED
              value: {{ .Values.agent.constraintChecker.enable | quote }}
            - name: CHECK_THRESHOLD
              value: {{ .Values.agent.constraintChecker.threshold | quote }}
            - name: CHECK_INTERVAL
              value: {{ .Values.agent.constraintChecker.interval | quote }}
            - name: KUBE_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: KUBE_GC_ENABLED
              value: {{ .Values.agent.kubeGCEnabled | quote }}
            - name: KUBE_GC_THRESHOLD
              value: {{ .Values.agent.kubeGCThreshold }}
            - name: KUBE_TASK_POD_CONFIG
              value: /etc/container-agent/taskpods
            - name: KUBE_TOKEN_SECRETS
              value: {{- if .Values.agent.customSecret -}}
                    {{- printf " %s" .Values.agent.customSecret -}},
                    {{- end }}
                    {{- if include "container-agent.create-secret" . -}}
                    {{- printf " %s" $fullName -}}
                    {{- end }}
            {{- with .Values.logging.image }}
            - name: KUBE_LOGGING_IMAGE
              value: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}:{{ .tag }}"
            {{- end }}
            - name: KUBE_LOGGING_SECRET
              value: {{ .Values.logging.serviceAccount.secret.name | quote }}
            - name: KUBE_AUTODETECT_PLATFORM
              value: {{ .Values.agent.autodetectPlatform | quote }}
          livenessProbe: {{ toYaml .Values.agent.livenessProbe | nindent 12 }}
          readinessProbe: {{ toYaml .Values.agent.readinessProbe | nindent 12 }}
        {{- if .Values.agent.resources }}
          resources: {{ toYaml .Values.agent.resources | nindent 12 }}
        {{- end }}
    {{- if .Values.agent.nodeSelector }}
      nodeSelector: {{ toYaml .Values.agent.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.agent.tolerations }}
      tolerations: {{ toYaml .Values.agent.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.agent.affinity }}
      affinity: {{ toYaml .Values.agent.affinity | nindent 8 }}
    {{- end }}
