{{- if include "container-agent.create-secret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "container-agent.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  {{- include "container-agent.tokens" . | indent 2 }}
{{- end -}}