apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-lambda-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ else }}
kind: Role
metadata:
  creationTimestamp: null
  name: ack-lambda-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups/status
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets
  verbs:
  - get
  - list
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets/status
  verbs:
  - get
  - list
- apiGroups:
  - iam.services.k8s.aws
  resources:
  - roles
  verbs:
  - get
  - list
- apiGroups:
  - iam.services.k8s.aws
  resources:
  - roles/status
  verbs:
  - get
  - list
- apiGroups:
  - kafka.services.k8s.aws
  resources:
  - clusters
  verbs:
  - get
  - list
- apiGroups:
  - kafka.services.k8s.aws
  resources:
  - clusters/status
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys/status
  verbs:
  - get
  - list
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - aliases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - aliases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - codesigningconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - codesigningconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - eventsourcemappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - eventsourcemappings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - functions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - functions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - functionurlconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - functionurlconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - layerversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lambda.services.k8s.aws
  resources:
  - layerversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mq.services.k8s.aws
  resources:
  - brokers
  verbs:
  - get
  - list
- apiGroups:
  - mq.services.k8s.aws
  resources:
  - brokers/status
  verbs:
  - get
  - list
- apiGroups:
  - s3.services.k8s.aws
  resources:
  - buckets
  verbs:
  - get
  - list
- apiGroups:
  - s3.services.k8s.aws
  resources:
  - buckets/status
  verbs:
  - get
  - list
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
