apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: pixie-operator-index
  namespace: {{ .Values.olmOperatorNamespace }}
spec:
  sourceType: grpc
  image: {{ if .Values.registry }}{{ .Values.registry }}/gcr.io-pixie-oss-pixie-prod-operator-bundle_index:0.0.1{{ else }}gcr.io/pixie-oss/pixie-prod/operator/bundle_index:0.0.1{{ end }}
  displayName: Pixie Vizier Operator
  publisher: px.dev
  updateStrategy:
    registryPoll:
      interval: 10m
