{{- if .Values.storageClass.efs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    porter.run/addon-name: {{ .Release.Name }}
    porter.run/addon-type: persistent-disk
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  volumeMode: {{ .Values.persistentVolume.volumeMode }}
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
  storageClassName: {{ .Release.Name }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storageClass.efs.fileSystemId }}:{{ .Release.Name }}-{{ .Release.Namespace }}
{{- end }} 