{{- if .Values.efs.fileSystemId -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    porter.run/addon-name: {{ .Release.Name }}
    porter.run/addon-type: persistent-disk
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.requestStorage }}
  storageClassName: {{ .Release.Name }}
{{- end }} 