{{ if .Values.awsEfsStorage }}
{{- range $index, $v := .Values.awsEfsStorage }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "docker-template.efsName" (dict "fullname" $.Values.fullnameOverride "index" $index) }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ $v.fileSystemId }}
  directoryPerms: "{{ default "700" $v.directoryPerms }}"
  reuseAccessPoint: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docker-template.efsName" (dict "fullname" $.Values.fullnameOverride "index" $index) }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "docker-template.efsName" (dict "fullname" $.Values.fullnameOverride "index" $index) }}
  resources:
    requests:
      storage: {{ default "5Gi" $v.storageSize }}
---
{{- end }}
{{- end }}
