{{- if and (not $.Values.statefulset.enabled) $.Values.bluegreen.enabled -}}
{{- if $.Values.autoscaling.enabled }}
{{- range $v, $tag := $.Values.bluegreen.imageTags }}
{{- if $.Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "docker-template.fullname" $ }}-{{ $tag }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "docker-template.fullname" $ }}-{{ $tag }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
{{- with $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with $.Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- if .Values.autoscaling.gpu }}
  {{- with .Values.autoscaling.targetGPUUtilizationPercentage }}
    - type: Pods
      pods:
        metric:
          name: gpu_utilization
        target:
          type: AverageValue
          averageValue: {{ . }}
    {{- end }}
    {{- with .Values.autoscaling.targetGPUMemoryUtilizationRatio }}
    - type: Pods
      pods:
        metric:
          name: gpu_memory_utilization_ratio
        target:
          type: AverageValue
          averageValue: {{ . }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}