{{- if .Values.privateIngress.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $allPrivateHosts := concat .Values.privateIngress.hosts  -}}
{{- $customPaths := .Values.privateIngress.custom_paths -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-private
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    {{- if and (gt (len $customPaths) 0) .Values.ingress.rewriteCustomPathsEnabled }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- end }}
    {{- if .Values.privateIngress.tls }}
    {{- if not (hasKey .Values.privateIngress.annotations "cert-manager.io/cluster-issuer")}}
    cert-manager.io/cluster-issuer: {{ .Values.privateIngress.clusterIssuer }}
    {{- end }}
    {{- end }}
    # provider-agnostic default annotations
    # if value is provided as "null" or null, it is unset
    # adding a fix for scenarios where ingress annotations are inside ingress.annotations.normal
    {{- if not (hasKey .Values.privateIngress.annotations "normal")}} 
    {{- if gt (len .Values.privateIngress.annotations) 0}}
    {{- range $k, $v := .Values.privateIngress.annotations }}
    {{- if $v}}
    {{- if and (not (eq $v "null")) $v}}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if hasKey .Values.privateIngress.annotations "normal"}}
    {{- if gt (len .Values.privateIngress.annotations.normal) 0}}
    {{- range $k, $v := .Values.privateIngress.annotations.normal }}
    {{- if $v}}
    {{- if and (not (eq $v "null")) $v}}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.privateIngress.privateIngressClass }}
  {{- if .Values.privateIngress.tls }}
  tls:
    - hosts:
        {{- range $allPrivateHosts }}
        - {{ . | quote }}
        {{- end }}
      {{- if .Values.privateIngress.secretName }}
      secretName: {{ .Values.privateIngress.secretName }}
      {{- else }}
      secretName: {{ include "docker-template.fullname" . }}
      {{- end }}
  {{- end }}
  rules:
  {{- range $allPrivateHosts }}
    - host: {{ . }}
      http:
        paths:
          {{ if gt (len $customPaths) 0 }}
          {{- range $customPaths }}
          - path: {{ .path }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}                
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
              {{- else }}
              serviceName: {{ .serviceName }} 
              servicePort: {{ .servicePort }}
              {{- end }}
          {{- end }}
          {{ else }}
          - {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
            {{- end }}
          {{ end }}
  {{- end }}
{{- end }}