apiVersion: v2
name: langfuse
version: 0.2.1
description: Open source LLM engineering platform - LLM observability, metrics, evaluations, prompt management.
type: application
keywords:
  - langfuse
  - llm
  - observability
  - prompt management
  - metrics
home: https://langfuse.com/
sources:
  - https://github.com/langfuse/langfuse
  - https://github.com/langfuse/langfuse-k8s
maintainers:
  - name: langfuse
    email: contact@langfuse.com
    url: https://langfuse.com/
icon: https://langfuse.com/langfuse_logo.png
appVersion: "2"