{{- $instances := default (list) .Values.cloudsql.instances -}}
{{- $instanceSecretSet := and (gt (len $instances) 0) (index $instances 0).serviceAccountJSONSecret -}}
{{- if and .Values.cloudsql.enabled (eq .Values.cloudsql.serviceAccountJSONSecret "") (not $instanceSecretSet) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "cloudsql.serviceAccountJSONSecret" . }}"
type: Opaque
stringData:
  service_account.json: {{ .Values.cloudsql.serviceAccountJSON | quote }}  
{{- end }}
