{{- if and .Values.cloudsql.enabled (eq .Values.cloudsql.serviceAccountJSONSecret "") -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "cloudsql.serviceAccountJSONSecret" . }}"
type: Opaque
stringData:
  service_account.json: {{ .Values.cloudsql.serviceAccountJSON | quote }}  
{{- end }}
