{{- if .Values.autoscaling.enabled }}
{{- if $.Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "docker-template.fullname" . }}
  annotations:
    validations.keda.sh/hpa-ownership: "false"
spec:
  {{- if .Values.autoscaling.behavior.enabled }}
  behavior:
    scaleDown:
      policies:
      - type: {{ .Values.autoscaling.behavior.scaleDown.type }}
        value: {{ .Values.autoscaling.behavior.scaleDown.value }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds }}
    scaleUp:
      policies:
      - type: {{ .Values.autoscaling.behavior.scaleUp.type }}
        value: {{ .Values.autoscaling.behavior.scaleUp.value }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds }}
  {{- end }}
  scaleTargetRef:
    {{- if and (.Values.deploymentStrategy) (eq .Values.deploymentStrategy.kind "blueGreen") }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "docker-template.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
{{- with .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- if .Values.autoscaling.gpu }}
  {{- with .Values.autoscaling.targetGPUUtilizationPercentage }}
    - type: Pods
      pods:
        metric:
          name: gpu_utilization
        target:
          type: AverageValue
          averageValue: {{ . }}
    {{- end }}
    {{- with .Values.autoscaling.targetGPUMemoryUtilizationRatio }}
    - type: Pods
      pods:
        metric:
          name: gpu_memory_utilization_ratio
        target:
          type: AverageValue
          averageValue: {{ . }}
    {{- end }}
{{- end }}
{{- end }}