{{- if .Values.podDisruptionBudget -}}
{{- if .Values.podDisruptionBudget.enabled  -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "docker-template.fullname" . }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  minAvailable: "{{ .Values.podDisruptionBudget.minAvailablePercentage }}%"
  selector:
    matchLabels:
      {{- include "docker-template.selectorLabels" . | nindent 6 }}
{{ end }}
{{ end }}
