{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "docker-template.fullname" . }}-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.pvc.existingPersistentVolume }}
  volumeName: {{ .Values.pvc.existingPersistentVolume }}
  {{- else }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
{{ end }}