{{- if .Values.keda.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $fullName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  fallback:
    failureThreshold: {{ .Values.keda.fallback.failureThreshold }}
    replicas: {{ .Values.keda.fallback.failureReplicas }}
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: {{ .Values.keda.hpa.scaleUp.stabilizationWindowSeconds }}
          policies:
          - type: {{ or .Values.keda.hpa.scaleUp.policy.type "Percent" }}
            value: {{ .Values.keda.hpa.scaleUp.policy.value }}
            periodSeconds: {{ .Values.keda.hpa.scaleUp.policy.periodSeconds }}
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.keda.hpa.scaleDown.stabilizationWindowSeconds }}
          policies:
          - type: {{ or .Values.keda.hpa.scaleDown.policy.type "Percent" }}
            value: {{ .Values.keda.hpa.scaleDown.policy.value }}
            periodSeconds: {{ .Values.keda.hpa.scaleDown.policy.periodSeconds }}
  {{- if .Values.keda.trigger }}
  triggers:
<<<<<<< HEAD
<<<<<<< HEAD
    {{- if .Values.keda.trigger.prometheus.enabled -}}
=======
    {{- if .Values.keda.trigger.enabled -}}
>>>>>>> master
=======
>>>>>>> main
    - type: prometheus
      metricType: {{ .Values.keda.trigger.metricType | default "AverageValue" }}
      metadata:
        # Required fields:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80
<<<<<<< HEAD
        metricName: {{ .Values.keda.trigger.prometheus.metricName }}
        query: {{ .Values.keda.trigger.prometheus.metricQuery }}
        threshold: '{{ .Values.keda.trigger.prometheus.metricThreshold }}'
    {{- end }}
    {{- if .Values.keda.trigger.datadog.enabled -}}
    - type: datadog
      metricType: Value
      metadata:
        query: "{{ .Values.keda.trigger.datadog.query }}"
        queryValue: "{{ .Values.keda.trigger.datadog.queryValue }}"
        activationQueryValue: "{{ .Values.keda.trigger.datadog.activationQueryValue }}"
        age: "{{ .Values.keda.trigger.datadog.age }}"
        metricUnavailableValue: "{{ .Values.keda.trigger.datadog.metricUnavailableValue }}"
    {{- end }}
{{- end }}
=======
        metricName: {{ .Values.keda.trigger.metricName }}
        query: {{ .Values.keda.trigger.metricQuery }}
        threshold: '{{ .Values.keda.trigger.metricThreshold }}'
  {{- end }}
  {{- if .Values.keda.triggers }}
  triggers:
  {{- toYaml .Values.keda.triggers | nindent 4 }}
  {{- end }}
{{- end }}
>>>>>>> master
