{{- if and .Values.keda.enabled .Values.keda.authentications -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- range $authName, $authConfig := .Values.keda.authentications }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $fullName }}-{{ $authName }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $authConfig.apiKey }}
  secretTargetRef:
    - parameter: apiKey
      name: {{ $authConfig.apiKey.secretName }}
      key: {{ $authConfig.apiKey.secretKey }}
  {{- end }}
  {{- if $authConfig.secretRefs }}
  secretTargetRef:
  {{- range $authConfig.secretRefs }}
    - parameter: {{ .parameter }}
      name: {{ .secretName }}
      key: {{ .secretKey }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}