apiVersion: rbac.authorization.k8s.io/v1
{{ if eq .Values.installScope "cluster" }}
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-apigatewayv2-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ else }}
kind: Role
metadata:
  creationTimestamp: null
  name: ack-apigatewayv2-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
{{ end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - apis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - apis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - authorizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - authorizers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - integrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - integrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - stages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - stages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - vpclinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - vpclinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - adoptedresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  verbs:
  - get
  - patch
  - update
