---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ include "ack-apigatewayv2-controller.app.fullname" . }}-writer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ack-apigatewayv2-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-apigatewayv2-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-apigatewayv2-controller.chart.name-version" . }}
rules:
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - apis
  - apimappings
  - authorizers
  - deployments
  - domainnames
  - integrations
  - routes
  - stages
  - vpclinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigatewayv2.services.k8s.aws
  resources:
  - apis
  - apimappings
  - authorizers
  - deployments
  - domainnames
  - integrations
  - routes
  - stages
  - vpclinks
  verbs:
  - get
  - patch
  - update
