{{- if and .Values.controller.wallarm.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.controller.wallarm.metrics.service.annotations }}
  annotations:
{{ toYaml .Values.controller.wallarm.metrics.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "nginx-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "nginx-ingress.controller.fullname" . }}-wallarm-metrics
spec:
  clusterIP: "{{ .Values.controller.metrics.service.clusterIP }}"
{{- if .Values.controller.wallarm.metrics.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.controller.wallarm.metrics.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.controller.wallarm.metrics.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.controller.wallarm.metrics.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.controller.wallarm.metrics.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.controller.wallarm.metrics.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - name: metrics
      port: {{ .Values.controller.wallarm.metrics.service.servicePort }}
      targetPort: metrics
  selector:
    app: {{ template "nginx-ingress.name" . }}
    component: "{{ .Values.controller.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.controller.wallarm.metrics.service.type }}"
{{- end }}
