---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-emrcontainers-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - emrcontainers.services.k8s.aws
  resources:
  - jobruns
  - virtualclusters
  verbs:
  - get
  - list
  - watch
