apiVersion: v1
name: datadog
version: 0.38.0
appVersion: "7"
description: Datadog Agent
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
keywords:
- monitoring
- alerting
- metric
maintainers:
  - name: Datadog
    email: support@datadoghq.com
