apiVersion: v1
name: datadog
version: 0.12.0
appVersion: "7"
description: Datadog Agent
keywords:
  - monitoring
  - alerting
  - metric
  - metrics
home: https://www.datadoghq.com
icon: https://datadog-live.imgix.net/img/dd_logo_70x75.png
sources:
  - https://app.datadoghq.com/account/settings#agent/kubernetes
  - https://github.com/DataDog/datadog-agent
maintainers:
  - name: Datadog
    email: support@datadoghq.com
