{
 "title": "App Rightsizing Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"default\"}, label_porter_run_app_name)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"default\", label_porter_run_app_name=\"$app\"}, label_porter_run_service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global App-Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RAM Requested By App-Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (label_porter_run_service_name, label_porter_run_app_name) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", resource=\"memory\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels {label_porter_run_app_name != \"\", label_porter_run_service_name != \"\"})",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "Total CPU Requested By App-Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum by (label_porter_run_service_name, label_porter_run_app_name) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", resource=\"cpu\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels {label_porter_run_app_name != \"\", label_porter_run_service_name != \"\"})",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "Total RAM Used by App-Service",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (label_porter_run_app_name, label_porter_run_service_name) (sum by (pod, namespace) (max by(container, pod, namespace) (container_memory_usage_bytes{namespace=\"default\", container!=\"\",container!=\"POD\"})) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels {label_porter_run_app_name != \"\", label_porter_run_service_name != \"\"})",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "Total CPU Used by App-Service",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum by(label_porter_run_app_name, label_porter_run_service_name) (sum by(pod, namespace) (max by(container, pod, namespace) (rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", container!=\"POD\"}[2m]))) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels{label_porter_run_app_name!=\"\", label_porter_run_service_name!=\"\"})",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization Percentage By App-Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(label_porter_run_app_name, label_porter_run_service_name) (sum by(pod, namespace) (max by(container, pod, namespace) (container_memory_usage_bytes{namespace=\"default\", container!=\"\",container!=\"POD\"})) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels {label_porter_run_app_name != \"\", label_porter_run_service_name != \"\"}) / sum by (label_porter_run_service_name, label_porter_run_app_name) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", resource=\"memory\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels {label_porter_run_app_name != \"\", label_porter_run_service_name != \"\"}) * 100",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Percentage By App-Service",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(label_porter_run_app_name, label_porter_run_service_name) (sum by(pod, namespace) (max by(container, pod, namespace) (rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", container!=\"POD\"}[2m]))) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels{label_porter_run_app_name!=\"\", label_porter_run_service_name!=\"\"}) / sum by (label_porter_run_service_name, label_porter_run_app_name) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", resource=\"cpu\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels {label_porter_run_app_name != \"\", label_porter_run_service_name != \"\"}) * 100",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "Per Selected App-Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Number of Running Pods (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (label_porter_run_app_name, label_porter_run_service_name) (kube_pod_status_ready{namespace=\"default\", condition=\"true\"} * on(pod, namespace) kube_pod_labels{label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"})",
     "legendFormat": "{{label_porter_run_app_name}}-{{label_porter_run_service_name}}"
    }
   ]
  },
  {
   "title": "Per Pod CPU Used (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "max by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", container!=\"POD\"}[5m]) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels { label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Per Pod CPU Requested (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "avg by (pod) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"cpu\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{k8s_deployment_name=\"prometheus-kube-state-metrics\", condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels{ label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"}) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Per Pod CPU Utilization Percentage (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", container!=\"\", container!=\"POD\"}[5m]) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels { label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"})/(avg by (pod) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"cpu\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{k8s_deployment_name=\"prometheus-kube-state-metrics\", condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels{ label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"}) != 0)*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Per Pod Memory Used (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_usage_bytes{namespace=\"default\", container!=\"\", container!=\"POD\"} * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels { label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Per Pod Memory Requested (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"memory\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{k8s_deployment_name=\"prometheus-kube-state-metrics\", condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels{ label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"}) != 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Per Pod Memory Utilization Percentage (Selected App-Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (pod) (container_memory_usage_bytes{namespace=\"default\", container!=\"\", container!=\"POD\"} * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels { label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"})/(avg by (pod) (max by (pod, namespace) (kube_pod_container_resource_requests{namespace=\"default\", container!=\"\", resource=\"memory\"}) * on(pod, namespace) group_left() max by (pod, namespace) (kube_pod_status_ready{k8s_deployment_name=\"prometheus-kube-state-metrics\", condition=\"true\"}) * on(pod, namespace) group_left(label_porter_run_app_name, label_porter_run_service_name) kube_pod_labels{ label_porter_run_app_name=\"$app\", label_porter_run_service_name=\"$service\"}) != 0) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}