{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,porter_run_app_name)"
    }
   },
   {
    "name": "Hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,Hostname)"
    }
   },
   {
    "name": "gpu",
    "label": "gpu",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,gpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu, porter_run_app_name) (gpu_memory_utilization_ratio{Hostname=~\"$Hostname\", gpu=~\"$gpu\", porter_run_app_name=~\"$application\"}) * 100",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(Hostname, gpu, porter_run_app_name) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${Hostname}\", gpu=~\"${gpu}\", porter_run_app_name=~\"${application}\"})",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(porter_run_app_name, Hostname, gpu) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"})",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(gpu, Hostname) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"})",
     "legendFormat": "{{Hostname}}__{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by(porter_run_app_name, Hostname, gpu) (DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"})",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by() (DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "avg by(porter_run_app_name, Hostname, gpu) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"}) * 1000000",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  },
  {
   "title": "Tensor Core Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(gpu, instance, porter_run_app_name) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"})",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg by(gpu, porter_run_app_name, Hostname) (DCGM_FI_DEV_FB_USED{Hostname=~\"$Hostname\", gpu=~\"${gpu}\", porter_run_app_name=~\"$application\"})",
     "legendFormat": "Application: \"{{porter_run_app_name}}\", Host: \"{{Hostname}}\", GPU: \"{{gpu}}\""
    }
   ]
  }
 ]
}