{
 "title": "General Visualization",
 "description": "This dashboard allows you to check basically everything that can be seen in Porter dashboard, but with more details and control:\n- App's CPU usage;\n- App's Memory usage;\n- App's number of instances;\n- App's amount of network data received;\n- App's number (and response status) of requests received;\n- App's logs\n- NGINX logs\n- Cluster's number of nodes",
 "tags": [
  "porter",
  "metrics",
  "logs",
  "cluster",
  "applications",
  "services",
  "networking",
  "nginx",
  "ingress",
  "k8s"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "App",
    "query": {
     "query": "label_values(porter_run_app_name)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values({label_porter_run_app_name=\"$App\"},label_porter_run_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(avg by (horizontalpodautoscaler) (label_replace(kube_pod_container_resource_requests{pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",namespace=\"default\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\",resource=\"cpu\",unit=\"core\"},\"horizontalpodautoscaler\", \"${App}-${Service}\", \"\", \"\")) * on(horizontalpodautoscaler) group_left() avg by (horizontalpodautoscaler) (kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"${App}-${Service}\",namespace=\"default\",metric_name=\"cpu\",metric_target_type=\"utilization\"}) / 100) or (avg by (horizontalpodautoscaler) (label_replace(kube_pod_container_resource_requests{pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",exported_namespace=\"default\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\",resource=\"cpu\",unit=\"core\"},\"horizontalpodautoscaler\", \"${App}-${Service}\", \"\", \"\")) * on(horizontalpodautoscaler) group_left() avg by (horizontalpodautoscaler) (kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"${App}-${Service}\",exported_namespace=\"default\",metric_name=\"cpu\",metric_target_type=\"utilization\"}) / 100)",
     "legendFormat": "Autoscaling threshold"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"default\",pod=~`${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*`,container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\"}[3m]))",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"default\",pod=~`${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*`,container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\"}[3m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "min(rate(container_cpu_usage_seconds_total{namespace=\"default\",pod=~`${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*`,container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\"}[3m]))",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "Logs - ${App}-${Service}",
   "type": "logs",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{porter_run_app_name=\"${App}\",porter_run_service_name=\"${Service}\"}"
    }
   ]
  },
  {
   "title": "Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(avg by (horizontalpodautoscaler) (label_replace(kube_pod_container_resource_requests{pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",namespace=\"default\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\",resource=\"memory\",unit=\"byte\"},\"horizontalpodautoscaler\", \"${App}-${Service}\", \"\", \"\")) * on(horizontalpodautoscaler) group_left() avg by (horizontalpodautoscaler) (kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"${App}-${Service}\",namespace=\"default\",metric_name=\"memory\",metric_target_type=\"utilization\"}) / 100 / 1000 / 1000) or (avg by (horizontalpodautoscaler) (label_replace(kube_pod_container_resource_requests{pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",exported_namespace=\"default\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\",resource=\"memory\",unit=\"byte\"},\"horizontalpodautoscaler\", \"${App}-${Service}\", \"\", \"\")) * on(horizontalpodautoscaler) group_left() avg by (horizontalpodautoscaler) (kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"${App}-${Service}\",exported_namespace=\"default\",metric_name=\"memory\",metric_target_type=\"utilization\"}) / 100 / 1000 / 1000)",
     "legendFormat": "Autoscaling threshold"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"default\",pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\"} / 1000 / 1000)",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(container_memory_usage_bytes{namespace=\"default\",pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\"} / 1000 / 1000)",
     "legendFormat": "Average"
    },
    {
     "expr": "min(container_memory_usage_bytes{namespace=\"default\",pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\",container!=\"POD\",container!=\"cloud-sql-proxy\",container!=\"\"} / 1000 / 1000)",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "Number of Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "k8s_hpa_max_replicas{k8s_hpa_name=\"keda-hpa-${App}-${Service}\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=\"${App}-${Service}\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "k8s_hpa_min_replicas{k8s_hpa_name=\"keda-hpa-${App}-${Service}\"}",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "Logs - NGINX Ingress",
   "type": "logs",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"}"
    }
   ]
  },
  {
   "title": "Received MiB per Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "max(rate(container_network_receive_bytes_total{namespace=\"default\",pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\"}[2m])) / 1000 / 1000",
     "legendFormat": "Maximum"
    },
    {
     "expr": "avg(rate(container_network_receive_bytes_total{namespace=\"default\",pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\"}[2m])) / 1000 / 1000",
     "legendFormat": "Average"
    },
    {
     "expr": "min(rate(container_network_receive_bytes_total{namespace=\"default\",pod=~\"${App}-${Service}-[a-z0-9]+(-[a-z0-9]+)*\"}[2m])) / 1000 / 1000",
     "legendFormat": "Minimum"
    }
   ]
  },
  {
   "title": "Number of requests per interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "round(sum by (status_code, ingress)(label_replace(increase(nginx_ingress_controller_requests_total{exported_namespace=~\"default\",ingress=\"${App}-${Service}\",service=\"${App}-${Service}\"}[2m]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")), 0.001) or round(sum by (status_code, ingress)(label_replace(increase(nginx_ingress_controller_requests_total{namespace=~\"default\",ingress=\"${App}-${Service}\",service=\"${App}-${Service}\"}[2m]), \"status_code\", \"${1}xx\", \"status\", \"(.)..\")), 0.001)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Number of nodes in the cluster",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(k8s_node_condition_ready{})",
     "legendFormat": "Ready Nodes"
    }
   ]
  }
 ]
}