annotations:
  category: Database
apiVersion: v2
appVersion: 11.10.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.x.x
description: An object-relational database management system (ORDBMS) with an emphasis on extensibility and standards-compliance.
home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
keywords:
  - postgresql
  - postgres
  - db
  - database
  - sql
  - replication
  - cluster
  - DATA_STORE
  - DATA_BASE
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
  - email: cedric@desaintmartin.fr
    name: desaintmartin
name: postgresql
sources:
  - https://github.com/bitnami/bitnami-docker-postgresql
  - https://www.postgresql.org/
version: 0.11.0
