#!/usr/bin/env bash
set -eo pipefail
main() {
  declare CHART_DIR="$1"
  if [[ "$CHART_DIR" != "addons/ack-chart" ]]; then
    return
  fi

  echo "Force setting repository for all dependencies"
  helm repo add porter-addons "$CHARTMUSEUM_URL"
  yq e '.dependencies[].repository = env(CHARTMUSEUM_URL)' -i "$CHART_DIR/Chart.yaml"
  echo "Updating dependencies"
  helm dependency update "$CHART_DIR"
  echo "Building dependencies"
  helm dependency build "$CHART_DIR"
  if [[ "$(git diff --name-only)" == "addons/ack-chart/Chart.lock" ]]; then
    git checkout -- "addons/ack-chart/Chart.lock"
  fi
}

main "$@"
