#!/usr/bin/env bash
set -eo pipefail
main() {
  declare CHART_DIR="$1"
  local lock_path="addons/ack-chart/Chart.lock"
  if [[ "$CHART_DIR" != "addons/ack-chart" ]]; then
    return
  fi

  echo "Force setting repository for all dependencies"
  helm repo add porter-addons "$CHARTMUSEUM_URL"
  yq e '.dependencies[].repository = env(CHARTMUSEUM_URL)' -i "$CHART_DIR/Chart.yaml"
  echo "Updating dependencies"
  helm dependency update "$CHART_DIR"
  echo "Building dependencies"
  helm dependency build "$CHART_DIR"

  if [[ "$(git diff --name-only)" == "$lock_path" ]] && [[ "$(git diff --stat "$lock_path" | tail -n 1)" == " 1 file changed, 1 insertion(+), 1 deletion(-)" ]]; then
    git checkout -- "$lock_path"
  fi
}

main "$@"
