{{- if or (ne .Values.image.repository "public.ecr.aws/o1j4x7p4/hello-porter-job") (.Values.global) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "docker-template.fullname" . }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - watch
      - list
      - create
      - delete
{{- end }}
