---
name: 'Sync remote directory'
description: 'Sync remote directory to a local directory'

inputs:
  remote_owner:
    description: Remote owner of the repository e.g. porter-dev
    required: true
  remote_repository:
    description: Remote repository name e.g. porter
    required: true
  remote_directory:
    description: Remote directory within the remote_repository to sync
    required: true
  target_directory:
    description: Directory within the current repo, where we would like to copy the files
    required: true
  github_token:
    description: 'Github token to use to pull and push the remote'
    required: true
  tag:
    description: 'Tag to checkout from the remote repository'
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Checkout ${{ inputs.remote_owner }}/${{ inputs.remote_repository }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        gh repo clone ${{ inputs.remote_owner }}/${{ inputs.remote_repository }}
        if [ ! -z "${{ inputs.tag }}" ]; then
          cd ${{ inputs.remote_repository }}
          git checkout ${{ inputs.tag }}
          echo "Checked out tag: ${{ inputs.tag }}"
          cd ..
        else
          echo "No tag specified, using default branch"
        fi
    - name: Replace symlinks with actual files
      shell: bash
      run: |
        find . -type l | while read -r link; do
          # Replace symlinks with actual files to ensure proper copying
          echo "Replacing symlink: $link with actual file"
          target=$(readlink -f "$link")
          rm "$link"
          cp -R "$target" "$link"
        done
    - name: Copy required directory
      shell: bash
      run: |
        rsync -av --cvs-exclude ${{ inputs.remote_repository }}/${{ inputs.remote_directory }}/ ${{ inputs.target_directory }}
        echo "${{ inputs.target_directory }}" >>vendored-charts
        sort -uo vendored-charts vendored-charts
    - name: Modify ack-chart if necessary
      shell: bash
      run: scripts/rebuild-ack-chart "${{ inputs.target_directory }}"
    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      with:
        add-paths: |
          vendored-charts
          ${{ inputs.target_directory }}
        title: "Sync: ${{ inputs.remote_owner }}/${{ inputs.remote_repository }} - ${{ inputs.remote_directory }} (Tag: ${{ inputs.tag }})"
        branch: "${{ inputs.target_directory }}"

