apiVersion: v1
name: ecr-chart
description: A Helm chart for the ACK service controller for Amazon Elastic Container Registry (ECR)
version: 1.5.1
appVersion: 1.5.1
home: https://github.com/aws-controllers-k8s/ecr-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/ecr-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: ECR Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ecr-maintainer
keywords:
  - aws
  - kubernetes
  - ecr
