# Default values for docker-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

auto_deploy: true

replicaCount: 1

terminationGracePeriodSeconds: 30
allowConcurrency: true

image:
  repository: public.ecr.aws/o1j4x7p4/hello-porter-job
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

container:
  port: 80
  command: ""
  env:
    normal:

schedule:
  enabled: false
  value: "*/5 * * * *"

resources:
  requests:
    cpu: 100m
    memory: 256Mi

paused: false

cloudsql:
  enabled: false
  connectionName: ""
  dbPort: 5432
  serviceAccountJSON: ""

sidecar:
  signalChildProcesses: true
  # The timeout value in seconds for the job run
  timeout: 3600
  resources:
    requests:
      cpu: 10m
      memory: 10Mi

retainFailedHooks: false
nodeSelector: {}
tolerations: []