apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: porter-ecr-secrets-updater-cronjob
spec:
  schedule: "{{ .Values.schedule.value }}"
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
          serviceAccountName: porter-ecr-secrets-updater-svc-acc
          containers:
            - name: update-secrets
              image: public.ecr.aws/o1j4x7p4/porter-ecr-secrets-updater:latest
              imagePullPolicy: Always
              env:
                - name: AWS_ACCESS_KEY_ID
                  value: "{{ .Values.awsCreds.awsAccessKeyID }}"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "{{ .Values.awsCreds.awsSecretAccessKey }}"
                - name: AWS_SESSION_TOKEN
                  value: "{{ .Values.awsCreds.awsSessionToken }}"
          restartPolicy: OnFailure
