---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ecr-writer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ecr.services.k8s.aws
  resources:
  - pullthroughcacherules

  - repositories

  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.services.k8s.aws
  resources:
  - pullthroughcacherules
  - repositories
  verbs:
  - get
  - patch
  - update
