apiVersion: v2
description: A Helm chart to deploy the New Relic Kubernetes Metrics Adapter.
name: newrelic-k8s-metrics-adapter
version: 1.2.0
appVersion: 0.4.2
home: https://hub.docker.com/r/newrelic/newrelic-k8s-metrics-adapter
sources:
  - https://github.com/newrelic/newrelic-k8s-metrics-adapter
  - https://github.com/newrelic/newrelic-k8s-metrics-adapter/tree/main/charts/newrelic-k8s-metrics-adapter
engine: gotpl
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg

dependencies:
  - name: common-library
    version: 1.1.1
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: nserrino
    url: https://github.com/nserrino
  - name: philkuz
    url: https://github.com/philkuz
  - name: htroisi
    url: https://github.com/htroisi
  - name: juanjjaramillo
    url: https://github.com/juanjjaramillo
  - name: svetlanabrennan
    url: https://github.com/svetlanabrennan
  - name: nrepai
    url: https://github.com/nrepai
  - name: csongnr
    url: https://github.com/csongnr
  - name: vuqtran88
    url: https://github.com/vuqtran88
  - name: xqi-nr
    url: https://github.com/xqi-nr

keywords:
  - infrastructure
  - newrelic
  - monitoring
