annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.0.10
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: Redis is an in-memory database that persists on disk with a key-value data model.
home: https://github.com/bitnami/charts/tree/main/bitnami/redis
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
  - redis
  - keyvalue
  - database
  - CACHE
  - DATA_STORE
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: redis
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/redis
version: 0.15.0
