apiVersion: v1
name: lambda-chart
description: A Helm chart for the ACK service controller for AWS Lambda (Lambda)
version: 1.3.5
appVersion: 1.3.5
home: https://github.com/aws-controllers-k8s/lambda-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/lambda-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Lambda Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/lambda-maintainer
keywords:
  - aws
  - kubernetes
  - lambda
