{{- if .Values.wildcard.enabled -}}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1"}}
apiVersion: cert-manager.io/v1
{{- else}}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: default
spec:
  secretName: wildcard-cert-tls
  issuerRef:
    # The issuer created previously
    name: letsencrypt-prod-wildcard
    kind: ClusterIssuer
  dnsNames:
  - '{{ .Values.wildcard.domain }}'
{{- end }}