{{- if .Values.wildcard.enabled -}}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1"}}
apiVersion: cert-manager.io/v1
{{- else}}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-wildcard
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-wildcard
    # Enable the HTTP-01 challenge provider
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
{{- end }}