name: 'Sync remote charts in PR using tar files'
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-remote-helm-charts-using-tar-files.yaml'
  workflow_dispatch:

jobs:
  sync-chart-using-tar-file:
    strategy:
      matrix:
        charts:
          - chart_url: https://github.com/external-secrets/external-secrets/releases/download/helm-chart-0.10.3/external-secrets-0.10.3.tgz
            target_directory: addons/external-secrets
            chart_name: external-secrets
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout porter-charts
        uses: actions/checkout@v4

      - name: Sync chart from tar file
        uses: ./.github/actions/sync-remote-directory-using-tar-file
        with:
          chart_url: ${{ matrix.charts.chart_url }}
          target_directory: ${{ matrix.charts.target_directory }}
          chart_name: ${{ matrix.charts.chart_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
