{{ if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ack-prometheusservice-controller.app.fullname" . }}-leaderelection
{{ if .Values.leaderElection.namespace }}
  namespace: {{ .Values.leaderElection.namespace }}
{{ else }}
  namespace: {{ .Release.Namespace }}
{{ end }}
  labels:
    app.kubernetes.io/name: {{ include "ack-prometheusservice-controller.app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    k8s-app: {{ include "ack-prometheusservice-controller.app.name" . }}
    helm.sh/chart: {{ include "ack-prometheusservice-controller.chart.name-version" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ack-prometheusservice-controller.app.fullname" . }}-leaderelection
subjects:
- kind: ServiceAccount
  name: {{ include "ack-prometheusservice-controller.service-account.name" . }}
  namespace: {{ .Release.Namespace }}{{- end }}
