---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-prometheusservice-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - prometheusservice.services.k8s.aws
  resources:
  - alertmanagerdefinitions
  - loggingconfigurations
  - rulegroupsnamespaces
  - workspaces
  verbs:
  - get
  - list
  - watch
